import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter'
import { Box, Toolbar } from '@mui/material'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import ThemeRegistry from '@/components/ThemeRegistry'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <ThemeRegistry>
            <Navbar />
            <Toolbar />
            <Box
              component="main"
              sx={{
                backgroundColor: 'background.default',
                minHeight: '100vh',
                px: { xs: 2, md: 4 },
                py: { xs: 3, md: 4 },
              }}
            >
              {children}
            </Box>
            <Footer />
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
